name: Upgrade Version
on:
  release:
    types: [published]

jobs:
  upgrade-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'Invoke-Locksmith.ps1'
          version-regexp: '\d+.\d+.\d+'
          repo-token: ${{ secrets.GITHUB_TOKEN }}